In [1]:
import pymysql
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import getpass

In [2]:
password=getpass.getpass()

········


In [3]:
connection_string='mysql+pymysql://root:'+password+'@127.0.0.1/sakila'

In [4]:
engine=create_engine(connection_string)

In [5]:
query_1 = '''
select i.film_id,
    round(avg(p.amount),2) avg_rental_cost,
    round(avg(timestampdiff(hour, r.rental_date, r.return_date)),2) as hours_rented,
     count(ifnull(r.rental_id, 0)) as num_rent_times
from rental r
join payment p on p.rental_id = r.rental_id
join inventory i on i.inventory_id = r.inventory_id
group by 1
order by 1,2,3,4;
'''
query_2 = '''
select
  act2.film_id,
  group_concat(act2.actor_id separator ',') actor_list,
  sum(act2.actor_fame) total_actor_fame,
  sum(act2.actor_influence) total_actor_influence
from (
  select fa.film_id, act1.*
    from (
      select
        fa1.actor_id,
        count(distinct(fa1.film_id)) actor_fame,
        count(distinct(fa2.actor_id)) actor_influence
        from
          film_actor fa1
          join film_actor fa2 on fa2.film_id = fa1.film_id
          group by fa1.actor_id
    ) act1
    join film_actor fa on fa.actor_id = act1.actor_id
) act2
group by act2.film_id;
'''
query_3 = '''
select  f.film_id,
       f.title,
     f.description,
     fc.category_id,
     f.language_id,
     avg(f.rental_duration) * 24  as avg_hours_rental_allowed,
     f.length / 60  as hours_length,
     avg(f.replacement_cost) as avg_replacement_cost,
     f.rating,
     f.special_features,
     count(fa.actor_id) actors_in_film
from film f
join film_category fc on fc.film_id = f.film_id
join film_actor fa on fa.film_id = f.film_id
group by 1,2,3,4,5,7,9,10
order by 1,4,5,6,7;'''

In [6]:
data_1=pd.read_sql(query_1,engine)
data_1

film_id  avg_rental_cost  hours_rented  num_rent_times
0          1             1.60        119.45              23
1          2             7.56        135.17               7
2          3             3.16         82.75              12
3          4             3.99        113.64              23
4          5             4.32        170.00              12
..       ...              ...           ...             ...
953      996             0.99        110.29               7
954      997             2.82        133.17               6
955      998             1.66        142.38               9
956      999             4.34        132.53              17
957     1000             6.93        108.52              31

[958 rows x 4 columns]

In [7]:
data_2=pd.read_sql(query_2,engine)
data_2

film_id                        actor_list  total_actor_fame  \
0          1  1,10,20,30,40,53,108,162,188,198             278.0   
1          2                      19,85,90,160             109.0   
2          3                    2,19,24,64,123             136.0   
3          4                  41,81,88,147,162             141.0   
4          5                 51,59,103,181,200             141.0   
..       ...                               ...               ...   
992      996                   3,27,84,163,170             131.0   
993      997                 23,37,124,155,198             169.0   
994      998              13,44,73,122,169,175             172.0   
995      999                 52,66,104,140,142             151.0   
996     1000                       155,166,178              76.0   

     total_actor_influence  
0                   1108.0  
1                    398.0  
2                    541.0  
3                    543.0  
4                    492.0  
..                     ...  
992                  542.0  
993                  615.0  
994                  626.0  
995                  537.0  
996                  313.0  

[997 rows x 4 columns]

In [8]:
data_3=pd.read_sql(query_3,engine)
data_3

film_id              title  \
0          1   ACADEMY DINOSAUR   
1          2     ACE GOLDFINGER   
2          3   ADAPTATION HOLES   
3          4   AFFAIR PREJUDICE   
4          5        AFRICAN EGG   
..       ...                ...   
992      996     YOUNG LANGUAGE   
993      997         YOUTH KICK   
994      998       ZHIVAGO CORE   
995      999  ZOOLANDER FICTION   
996     1000          ZORRO ARK   

                                           description  category_id  \
0    A Epic Drama of a Feminist And a Mad Scientist...            6   
1    A Astounding Epistle of a Database Administrat...           11   
2    A Astounding Reflection of a Lumberjack And a ...            6   
3    A Fanciful Documentary of a Frisbee And a Lumb...           11   
4    A Fast-Paced Documentary of a Pastry Chef And ...            8   
..                                                 ...          ...   
992  A Unbelieveable Yarn of a Boat And a Database ...            6   
993  A Touching Drama of a Teacher And a Cat who mu...           12   
994  A Fateful Yarn of a Composer And a Man who mus...           11   
995  A Fateful Reflection of a Waitress And a Boat ...            3   
996  A Intrepid Panorama of a Mad Scientist And a B...            5   

     language_id  avg_hours_rental_allowed  hours_length  \
0              1                     144.0        1.4333   
1              1                      72.0        0.8000   
2              1                     168.0        0.8333   
3              1                     120.0        1.9500   
4              1                     144.0        2.1667   
..           ...                       ...           ...   
992            1                     144.0        3.0500   
993            1                      96.0        2.9833   
994            1                     144.0        1.7500   
995            1                     120.0        1.6833   
996            1                      72.0        0.8333   

     avg_replacement_cost rating                         special_features  \
0                   20.99     PG         Deleted Scenes,Behind the Scenes   
1                   12.99      G                  Trailers,Deleted Scenes   
2                   18.99  NC-17                  Trailers,Deleted Scenes   
3                   26.99      G           Commentaries,Behind the Scenes   
4                   22.99      G                           Deleted Scenes   
..                    ...    ...                                      ...   
992                  9.99      G               Trailers,Behind the Scenes   
993                 14.99  NC-17               Trailers,Behind the Scenes   
994                 10.99  NC-17                           Deleted Scenes   
995                 28.99      R                  Trailers,Deleted Scenes   
996                 18.99  NC-17  Trailers,Commentaries,Behind the Scenes   

     actors_in_film  
0                10  
1                 4  
2                 5  
3                 5  
4                 5  
..              ...  
992               5  
993               5  
994               6  
995               5  
996               3  

[997 rows x 11 columns]

In [9]:
data_new=pd.merge(data_2,data_3,how='left',on='film_id')

In [10]:
df=pd.merge(data_new,data_1,how='left',on='film_id')

In [11]:
df.describe()

film_id  total_actor_fame  total_actor_influence  category_id  \
count   997.000000        997.000000             997.000000   997.000000   
mean    500.618857        154.539619             589.052156     8.465396   
std     288.937486         66.239341             256.909348     4.606183   
min       1.000000         18.000000              83.000000     1.000000   
25%     250.000000        109.000000             410.000000     5.000000   
50%     501.000000        147.000000             555.000000     8.000000   
75%     750.000000        199.000000             763.000000    13.000000   
max    1000.000000        440.000000            1710.000000    16.000000   

       language_id  avg_hours_rental_allowed  hours_length  \
count        997.0                997.000000    997.000000   
mean           1.0                119.590772      1.919158   
std            0.0                 33.827715      0.673097   
min            1.0                 72.000000      0.766700   
25%            1.0                 96.000000      1.333300   
50%            1.0                120.000000      1.900000   
75%            1.0                144.000000      2.483300   
max            1.0                168.000000      3.083300   

       avg_replacement_cost  actors_in_film  avg_rental_cost  hours_rented  \
count            997.000000      997.000000       955.000000    955.000000   
mean              19.975958        5.478435         4.213141    119.788147   
std                6.048814        2.321712         1.817873     16.830381   
min                9.990000        1.000000         0.990000     45.860000   
25%               14.990000        4.000000         2.880000    109.250000   
50%               19.990000        5.000000         3.990000    120.430000   
75%               24.990000        7.000000         5.710000    130.250000   
max               29.990000       15.000000         8.670000    172.330000   

       num_rent_times  
count      955.000000  
mean        16.758115  
std          6.682303  
min          4.000000  
25%         11.000000  
50%         16.000000  
75%         22.000000  
max         34.000000

In [12]:
df.isnull().sum()

film_id                      0
actor_list                   0
total_actor_fame             0
total_actor_influence        0
title                        0
description                  0
category_id                  0
language_id                  0
avg_hours_rental_allowed     0
hours_length                 0
avg_replacement_cost         0
rating                       0
special_features             0
actors_in_film               0
avg_rental_cost             42
hours_rented                42
num_rent_times              42
dtype: int64

In [13]:
df.dropna(axis=0,inplace=True)

In [14]:
df.columns

Index(['film_id', 'actor_list', 'total_actor_fame', 'total_actor_influence',
       'title', 'description', 'category_id', 'language_id',
       'avg_hours_rental_allowed', 'hours_length', 'avg_replacement_cost',
       'rating', 'special_features', 'actors_in_film', 'avg_rental_cost',
       'hours_rented', 'num_rent_times'],
      dtype='object')

In [15]:
df

film_id                        actor_list  total_actor_fame  \
0          1  1,10,20,30,40,53,108,162,188,198             278.0   
1          2                      19,85,90,160             109.0   
2          3                    2,19,24,64,123             136.0   
3          4                  41,81,88,147,162             141.0   
4          5                 51,59,103,181,200             141.0   
..       ...                               ...               ...   
992      996                   3,27,84,163,170             131.0   
993      997                 23,37,124,155,198             169.0   
994      998              13,44,73,122,169,175             172.0   
995      999                 52,66,104,140,142             151.0   
996     1000                       155,166,178              76.0   

     total_actor_influence              title  \
0                   1108.0   ACADEMY DINOSAUR   
1                    398.0     ACE GOLDFINGER   
2                    541.0   ADAPTATION HOLES   
3                    543.0   AFFAIR PREJUDICE   
4                    492.0        AFRICAN EGG   
..                     ...                ...   
992                  542.0     YOUNG LANGUAGE   
993                  615.0         YOUTH KICK   
994                  626.0       ZHIVAGO CORE   
995                  537.0  ZOOLANDER FICTION   
996                  313.0          ZORRO ARK   

                                           description  category_id  \
0    A Epic Drama of a Feminist And a Mad Scientist...            6   
1    A Astounding Epistle of a Database Administrat...           11   
2    A Astounding Reflection of a Lumberjack And a ...            6   
3    A Fanciful Documentary of a Frisbee And a Lumb...           11   
4    A Fast-Paced Documentary of a Pastry Chef And ...            8   
..                                                 ...          ...   
992  A Unbelieveable Yarn of a Boat And a Database ...            6   
993  A Touching Drama of a Teacher And a Cat who mu...           12   
994  A Fateful Yarn of a Composer And a Man who mus...           11   
995  A Fateful Reflection of a Waitress And a Boat ...            3   
996  A Intrepid Panorama of a Mad Scientist And a B...            5   

     language_id  avg_hours_rental_allowed  hours_length  \
0              1                     144.0        1.4333   
1              1                      72.0        0.8000   
2              1                     168.0        0.8333   
3              1                     120.0        1.9500   
4              1                     144.0        2.1667   
..           ...                       ...           ...   
992            1                     144.0        3.0500   
993            1                      96.0        2.9833   
994            1                     144.0        1.7500   
995            1                     120.0        1.6833   
996            1                      72.0        0.8333   

     avg_replacement_cost rating                         special_features  \
0                   20.99     PG         Deleted Scenes,Behind the Scenes   
1                   12.99      G                  Trailers,Deleted Scenes   
2                   18.99  NC-17                  Trailers,Deleted Scenes   
3                   26.99      G           Commentaries,Behind the Scenes   
4                   22.99      G                           Deleted Scenes   
..                    ...    ...                                      ...   
992                  9.99      G               Trailers,Behind the Scenes   
993                 14.99  NC-17               Trailers,Behind the Scenes   
994                 10.99  NC-17                           Deleted Scenes   
995                 28.99      R                  Trailers,Deleted Scenes   
996                 18.99  NC-17  Trailers,Commentaries,Behind the Scenes   

     actors_in_film  avg_rental_cost  hours_rented  num_rent_times  
0                10            

In [16]:
df=df.drop(['language_id','title','description','special_features','actor_list','total_actor_fame','film_id'],axis=1)

In [17]:
df

total_actor_influence  category_id  avg_hours_rental_allowed  \
0                   1108.0            6                     144.0   
1                    398.0           11                      72.0   
2                    541.0            6                     168.0   
3                    543.0           11                     120.0   
4                    492.0            8                     144.0   
..                     ...          ...                       ...   
992                  542.0            6                     144.0   
993                  615.0           12                      96.0   
994                  626.0           11                     144.0   
995                  537.0            3                     120.0   
996                  313.0            5                      72.0   

     hours_length  avg_replacement_cost rating  actors_in_film  \
0          1.4333                 20.99     PG              10   
1          0.8000                 12.99      G               4   
2          0.8333                 18.99  NC-17               5   
3          1.9500                 26.99      G               5   
4          2.1667                 22.99      G               5   
..            ...                   ...    ...             ...   
992        3.0500                  9.99      G               5   
993        2.9833                 14.99  NC-17               5   
994        1.7500                 10.99  NC-17               6   
995        1.6833                 28.99      R               5   
996        0.8333                 18.99  NC-17               3   

     avg_rental_cost  hours_rented  num_rent_times  
0               1.60        119.45            23.0  
1               7.56        135.17             7.0  
2               3.16         82.75            12.0  
3               3.99        113.64            23.0  
4               4.32        170.00            12.0  
..               ...           ...             ...  
992             0.99        110.29             7.0  
993             2.82        133.17             6.0  
994             1.66        142.38             9.0  
995             4.34        132.53            17.0  
996             6.93        108.52            31.0  

[955 rows x 10 columns]

In [59]:
y=df['num_rent_times']

In [49]:
y=list(y)

In [19]:
X=df.drop('num_rent_times',axis=1)

In [20]:
x_cat=X['rating']

In [21]:
x_cat=pd.get_dummies(x_cat,drop_first=True).head()
x_cat

NC-17  PG  PG-13  R
0      0   1      0  0
1      0   0      0  0
2      1   0      0  0
3      0   0      0  0
4      0   0      0  0

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
pd.DataFrame(OneHotEncoder(drop='first').fit_transform(x_cat).toarray(),
             columns=OneHotEncoder(drop='first').fit(x_cat).get_feature_names(input_features=x_cat.columns)).head()

NC-17_1  PG_1
0      0.0   1.0
1      0.0   0.0
2      1.0   0.0
3      0.0   0.0
4      0.0   0.0

In [22]:
x_num=X.drop(['rating'],axis=1)
x_num

total_actor_influence  category_id  avg_hours_rental_allowed  \
0                   1108.0            6                     144.0   
1                    398.0           11                      72.0   
2                    541.0            6                     168.0   
3                    543.0           11                     120.0   
4                    492.0            8                     144.0   
..                     ...          ...                       ...   
992                  542.0            6                     144.0   
993                  615.0           12                      96.0   
994                  626.0           11                     144.0   
995                  537.0            3                     120.0   
996                  313.0            5                      72.0   

     hours_length  avg_replacement_cost  actors_in_film  avg_rental_cost  \
0          1.4333                 20.99              10             1.60   
1          0.8000                 12.99               4             7.56   
2          0.8333                 18.99               5             3.16   
3          1.9500                 26.99               5             3.99   
4          2.1667                 22.99               5             4.32   
..            ...                   ...             ...              ...   
992        3.0500                  9.99               5             0.99   
993        2.9833                 14.99               5             2.82   
994        1.7500                 10.99               6             1.66   
995        1.6833                 28.99               5             4.34   
996        0.8333                 18.99               3             6.93   

     hours_rented  
0          119.45  
1          135.17  
2           82.75  
3          113.64  
4          170.00  
..            ...  
992        110.29  
993        133.17  
994        142.38  
995        132.53  
996        108.52  

[955 rows x 8 columns]

In [23]:
x_num=x_num.reset_index(drop=True)

In [24]:
x_num.columns

Index(['total_actor_influence', 'category_id', 'avg_hours_rental_allowed',
       'hours_length', 'avg_replacement_cost', 'actors_in_film',
       'avg_rental_cost', 'hours_rented'],
      dtype='object')

In [25]:
def nomarlize(x):
    x_mean=x.mean(axis=0)
    x_std=x.std(axis=0)
    x_std[x_std==0]=1
    x=(x-x_mean)/x_std
    return x

In [26]:
x_num=nomarlize(x_num)
x_num

total_actor_influence  category_id  avg_hours_rental_allowed  \
0                 2.020124    -0.535702                  0.734697   
1                -0.753352     0.548646                 -1.400096   
2                -0.194751    -0.535702                  1.446294   
3                -0.186938     0.548646                  0.023099   
4                -0.386160    -0.101963                  0.734697   
..                     ...          ...                       ...   
950              -0.190844    -0.535702                  0.734697   
951               0.094316     0.765515                 -0.688499   
952               0.137285     0.548646                  0.734697   
953              -0.210376    -1.186310                  0.023099   
954              -1.085388    -0.752571                 -1.400096   

     hours_length  avg_replacement_cost  actors_in_film  avg_rental_cost  \
0       -0.726319              0.154873        1.948690        -1.437472   
1       -1.666157             -1.165692       -0.645639         1.841085   
2       -1.616738             -0.175269       -0.213251        -0.579326   
3        0.040480              1.145296       -0.213251        -0.122749   
4        0.362070              0.485014       -0.213251         0.058782   
..            ...                   ...             ...              ...   
950      1.672915             -1.660904       -0.213251        -1.773029   
951      1.573931             -0.835551       -0.213251        -0.766358   
952     -0.256326             -1.495833        0.219137        -1.404466   
953     -0.355311              1.475437       -0.213251         0.069784   
954     -1.616738             -0.175269       -1.078028         1.494526   

     hours_rented  
0       -0.020091  
1        0.913934  
2       -2.200672  
3       -0.365300  
4        2.983406  
..            ...  
950     -0.564345  
951      0.795101  
952      1.342326  
953      0.757075  
954     -0.669512  

[955 rows x 8 columns]

In [38]:
X=pd.concat([x_num,x_cat],axis=1)
X

total_actor_influence  category_id  avg_hours_rental_allowed  \
0                 2.020124    -0.535702                  0.734697   
1                -0.753352     0.548646                 -1.400096   
2                -0.194751    -0.535702                  1.446294   
3                -0.186938     0.548646                  0.023099   
4                -0.386160    -0.101963                  0.734697   
..                     ...          ...                       ...   
950              -0.190844    -0.535702                  0.734697   
951               0.094316     0.765515                 -0.688499   
952               0.137285     0.548646                  0.734697   
953              -0.210376    -1.186310                  0.023099   
954              -1.085388    -0.752571                 -1.400096   

     hours_length  avg_replacement_cost  actors_in_film  avg_rental_cost  \
0       -0.726319              0.154873        1.948690        -1.437472   
1       -1.666157             -1.165692       -0.645639         1.841085   
2       -1.616738             -0.175269       -0.213251        -0.579326   
3        0.040480              1.145296       -0.213251        -0.122749   
4        0.362070              0.485014       -0.213251         0.058782   
..            ...                   ...             ...              ...   
950      1.672915             -1.660904       -0.213251        -1.773029   
951      1.573931             -0.835551       -0.213251        -0.766358   
952     -0.256326             -1.495833        0.219137        -1.404466   
953     -0.355311              1.475437       -0.213251         0.069784   
954     -1.616738             -0.175269       -1.078028         1.494526   

     hours_rented  NC-17   PG  PG-13    R  
0       -0.020091    0.0  1.0    0.0  0.0  
1        0.913934    0.0  0.0    0.0  0.0  
2       -2.200672    1.0  0.0    0.0  0.0  
3       -0.365300    0.0  0.0    0.0  0.0  
4        2.983406    0.0  0.0    0.0  0.0  
..            ...    ...  ...    ...  ...  
950     -0.564345    NaN  NaN    NaN  NaN  
951      0.795101    NaN  NaN    NaN  NaN  
952      1.342326    NaN  NaN    NaN  NaN  
953      0.757075    NaN  NaN    NaN  NaN  
954     -0.669512    NaN  NaN    NaN  NaN  

[955 rows x 12 columns]

In [41]:
X=X.fillna(0)

In [28]:
from sklearn.model_selection import train_test_split as tts

In [51]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.4)

In [52]:
import warnings
warnings.simplefilter('ignore')

In [53]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [54]:
X_train_wi=sm.add_constant(X_train)

In [55]:
model=sm.OLS(y_train,X_train_wi).fit()

In [56]:
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     1.558
Date:                Fri, 06 Nov 2020   Prob (F-statistic):              0.116
Time:                        21:29:27   Log-Likelihood:                -1898.4
No. Observations:                 573   AIC:                             3819.
Df Residuals:                     562   BIC:                             3867.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                   

In [60]:
from sklearn.linear_model import LinearRegression as LinReg

In [61]:
linreg=LinReg()

In [62]:
linreg.fit(X_train,y_train)

LinearRegression()

In [70]:
y_pred_linreg=linreg.predict(X_test)

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
lr_model = LogisticRegression()

In [68]:
lr_model.fit(X_train,y_train)

LogisticRegression()

In [69]:
y_pred_lr=linreg.predict(X_test)
y_pred_lr

array([14.86613393, 16.85751383, 18.04143864, 15.29767584, 15.22575247,
       16.4549662 , 15.6815067 , 16.83699454, 16.16595598, 16.48932205,
       16.25266878, 16.66019512, 14.5266381 , 16.50244632, 16.81174289,
       16.31579176, 18.11639919, 16.89192566, 15.58960169, 16.5665357 ,
       18.94594899, 17.78456121, 16.9152237 , 17.13804397, 15.79925844,
       17.45077864, 17.86750912, 16.2383351 , 16.19974591, 18.05713028,
       17.40229298, 17.79871071, 16.83949011, 17.9550056 , 18.98905899,
       16.46835131, 16.79897441, 14.92380056, 17.14617356, 14.73729224,
       17.74906709, 15.82027344, 15.95811401, 17.2726958 , 15.5682821 ,
       15.37322734, 17.21431938, 15.24914333, 16.17969761, 18.05354742,
       15.53014729, 16.53309468, 18.89063236, 15.535659  , 15.00239406,
       13.8254174 , 18.84218816, 15.62259342, 16.55036591, 17.74904477,
       16.21221223, 18.18881628, 14.82249647, 16.30016148, 17.12883407,
       17.20850237, 15.43859556, 18.1427689 , 15.69714086, 16.30

In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [73]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.4,random_state=0)

In [74]:
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [75]:
predict_results=LR.predict(X_test)
print(accuracy_score(predict_results, y_test))

0.02617801047120419


In [78]:
conf_mat = confusion_matrix(y_test, predict_results)
print(conf_mat)

[[0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 1 2 1 3 0 2 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [2 3 0 1 2 1 2 0 0 0 1 0 0 1 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 2 1 1 0 0 0 1 2 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 0 0 0 1 1 1 1 2 0 1 0 3 1 2 2 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 0 2 0 0 1 1 0 2 1 0 0 3 2 0 1 0 0 1 0 0 0 0 0 0]
 [1 0 0 1 1 0 1 0 0 0 2 0 0 1 0 1 3 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 4 2 0 0 1 0 0 1 1 0 1 2 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 3 0 1 0 0 1 1 0 1 4 2 3 4 1 1 0 0 0 0 0 0 0 0 0 0]
 [2 3 0 0 1 1 2 0 2 2 0 0 0 2 2 1 1 1 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 2 0 0 1 1 0 1 4 0 0 1 2 2 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 1 3 0 1 1 0 1 0 4 0 0 5 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 2 1 1 0 1 0 0 1 2 1 2 4 1 2 0 0 2 0 0 0 0 0 0]
 [0 0 1 0 1 1 2 1 0 0 1 2 2 1 1 0 4 2 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 2 0 0 1 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 1 3 0 0 0 0 1 0 0 2 1 2 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 4 0 1 

In [79]:
print(classification_report(y_test, predict_results))

              precision    recall  f1-score   support

         5.0       0.00      0.00      0.00         3
         6.0       0.00      0.00      0.00        13
         7.0       0.00      0.00      0.00        17
         8.0       0.00      0.00      0.00        12
         9.0       0.00      0.00      0.00        22
        10.0       0.00      0.00      0.00        18
        11.0       0.03      0.08      0.04        13
        12.0       0.00      0.00      0.00        14
        13.0       0.00      0.00      0.00        24
        14.0       0.20      0.10      0.13        21
        15.0       0.06      0.06      0.06        17
        16.0       0.06      0.05      0.05        21
        17.0       0.00      0.00      0.00        22
        18.0       0.03      0.05      0.04        20
        19.0       0.00      0.00      0.00        12
        20.0       0.07      0.07      0.07        15
        21.0       0.03      0.11      0.05        18
        22.0       0.00    